workflows:
  android-release:
    name: Android Release Build
    max_build_duration: 60
    environment:
      java: 21
      node: 22
    scripts:
      - name: Install dependencies
        script: npm ci
      - name: Build web app
        script: npm run build
      - name: Setup Capacitor
        script: npx cap sync android
      - name: Build APK
        script: |
          cd android
          ./gradlew assembleRelease
    artifacts:
      - android/app/build/outputs/**/*.apk

  ios-release:
    name: iOS Release Build
    max_build_duration: 60
    instance_type: mac_mini_m2
    environment:
      node: 22
      xcode: latest
    scripts:
      - name: Install dependencies
        script: npm ci
      - name: Build web app
        script: npm run build
      - name: Setup Capacitor
        script: npx cap sync ios
      - name: Build IPA
        script: |
          cd ios/App
          xcodebuild -workspace App.xcworkspace -scheme App -configuration Release -archivePath build/App.xcarchive archive
          xcodebuild -exportArchive -archivePath build/App.xcarchive -exportPath build -exportOptionsPlist ExportOptions.plist
    artifacts:
      - ios/App/build/*.ipa
