workflows:

  android-release:
    name: Android Release Build
    max_build_duration: 60
    instance_type: linux_x2
    environment:
      java: 17
      node: 20
      vars:
        ANDROID_KEYSTORE_PASSWORD: $ANDROID_KEYSTORE_PASSWORD
        ANDROID_KEY_ALIAS: $ANDROID_KEY_ALIAS
        ANDROID_KEY_PASSWORD: $ANDROID_KEY_PASSWORD
      android_signing:
        - appship_keystore
    scripts:
      - name: Download and extract project
        script: |
          echo "Downloading project from: $APP_ZIP_URL"
          curl -L -o project.zip "$APP_ZIP_URL"
          unzip -o project.zip -d ./app
          cd app
          if [ -d "capacitor-project" ]; then
            mv capacitor-project/* .
            rm -rf capacitor-project
          fi
          ls -la
      - name: Install dependencies
        script: |
          cd app
          npm ci || npm install
      - name: Add and sync Capacitor
        script: |
          cd app
          rm -rf android
          npx cap add android
          npx cap sync android
      - name: Build Android
        script: |
          cd app/android
          chmod +x gradlew
          ./gradlew assembleRelease
    artifacts:
      - app/android/app/build/outputs/**/*.apk
      - app/android/app/build/outputs/**/*.aab
    publishing:
      scripts:
        - name: Notify build result
          script: |
            if [ "$CM_BUILD_STEP_STATUS" == "success" ]; then
              STATUS="finished"
            else
              STATUS="failed"
            fi
            echo "Build $STATUS - Sending webhook"
            PAYLOAD=$(python3 -c "
            import json
            print(json.dumps({
              'buildId': '$CM_BUILD_ID',
              'status': '$STATUS',
              'platform': 'android',
              'workflowId': 'android-release',
              'environment': {'variables': {'USER_APP_ID': '$USER_APP_ID'}},
              'artefacts': [{'url': '''$CM_ARTIFACT_LINKS''', 'type': 'apk'}],
              'finishedAt': '$(date -u +%Y-%m-%dT%H:%M:%SZ)'
            }))
            ")
            curl -X POST "$SUPABASE_URL/functions/v1/codemagic-webhook" \
              -H "Content-Type: application/json" \
              -d "$PAYLOAD"

  ios-release:
    name: iOS Release Build
    max_build_duration: 90
    instance_type: mac_mini_m2
    environment:
      xcode: latest
      node: 20
      cocoapods: default
    scripts:
      - name: Download and extract project
        script: |
          echo "Downloading project from: $APP_ZIP_URL"
          curl -L -o project.zip "$APP_ZIP_URL"
          unzip -o project.zip -d ./app
          cd app
          if [ -d "capacitor-project" ]; then
            mv capacitor-project/* .
            rm -rf capacitor-project
          fi
          ls -la
      - name: Install dependencies
        script: |
          cd app
          npm ci || npm install
      - name: Add and sync Capacitor
        script: |
          cd app
          rm -rf ios
          npx cap add ios
          npx cap sync ios
          cd ios/App
          sed -i '' "s/PRODUCT_BUNDLE_IDENTIFIER = .*/PRODUCT_BUNDLE_IDENTIFIER = ${BUNDLE_ID};/g" App.xcodeproj/project.pbxproj
          sed -i '' "s/DEVELOPMENT_TEAM = .*/DEVELOPMENT_TEAM = ${TEAM_ID};/g" App.xcodeproj/project.pbxproj
      - name: Install CocoaPods
        script: |
          cd app/ios/App
          pod install
      - name: Set up code signing
        script: |
          set -e
          keychain initialize
          printf '%s' "$APP_STORE_CONNECT_KEY_CONTENT" | base64 -D > /tmp/AuthKey.p8
          if [ -z "$CM_CERTIFICATE_PRIVATE_KEY" ]; then
            openssl genrsa -out /tmp/cert_key.pem 2048
          else
            echo "$CM_CERTIFICATE_PRIVATE_KEY" > /tmp/cert_key.pem
          fi
          echo "=== Fetching signing files for $BUNDLE_ID ==="
          app-store-connect fetch-signing-files "$BUNDLE_ID" \
            --type IOS_APP_STORE \
            --key-id "$APP_STORE_CONNECT_KEY_ID" \
            --issuer-id "$APP_STORE_CONNECT_ISSUER_ID" \
            --private-key "$(cat /tmp/AuthKey.p8)" \
            --certificate-key "$(cat /tmp/cert_key.pem)" \
            --create
          echo "=== Adding certificates to keychain ==="
          keychain add-certificates
          echo "=== Applying profiles to Xcode project ==="
          cd app/ios/App
          xcode-project use-profiles
          echo "=== Checking project signing settings ==="
          grep -c "PROVISIONING_PROFILE" App.xcodeproj/project.pbxproj || echo "WARNING: No provisioning profiles found in project!"
      - name: Build iOS
        script: |
          cd app/ios/App
          xcode-project build-ipa \
            --workspace App.xcworkspace \
            --scheme App \
            --archive-flags "CODE_SIGN_STYLE=Manual"
    artifacts:
      - app/ios/App/build/ios/ipa/*.ipa
      - app/ios/App/**/*.xcarchive
    publishing:
      scripts:
        - name: Notify build result
          script: |
            if [ "$CM_BUILD_STEP_STATUS" == "success" ]; then
              STATUS="finished"
            else
              STATUS="failed"
            fi
            echo "Build $STATUS - Sending webhook"
            PAYLOAD=$(python3 -c "
            import json
            print(json.dumps({
              'buildId': '$CM_BUILD_ID',
              'status': '$STATUS',
              'platform': 'ios',
              'workflowId': 'ios-release',
              'environment': {'variables': {'USER_APP_ID': '$USER_APP_ID'}},
              'artefacts': [{'url': '''$CM_ARTIFACT_LINKS''', 'type': 'ipa'}],
              'finishedAt': '$(date -u +%Y-%m-%dT%H:%M:%SZ)'
            }))
            ")
            curl -X POST "$SUPABASE_URL/functions/v1/codemagic-webhook" \
              -H "Content-Type: application/json" \
              -d "$PAYLOAD"

  android-submit:
    name: Android Play Store Submission
    max_build_duration: 30
    instance_type: linux_x2
    environment:
      java: 17
      ruby: 3.2
    scripts:
      - name: Download artifact
        script: |
          mkdir -p artifacts
          echo "Downloading artifact from: $ARTIFACT_URL"
          curl -L -o artifacts/app.apk "$ARTIFACT_URL"
          if [[ "$ARTIFACT_URL" == *".aab"* ]]; then
            mv artifacts/app.apk artifacts/app.aab
          fi
          ls -la artifacts/
      - name: Setup Google Play credentials
        script: |
          echo "$GOOGLE_PLAY_JSON_KEY" | base64 -d > google-play-key.json
          echo "Google Play credentials configured"
      - name: Install Fastlane
        script: gem install fastlane
      - name: Setup metadata and Fastfile
        script: |
          mkdir -p fastlane/metadata/android/en-US/changelogs
          echo "${APP_NAME:-My App}" > fastlane/metadata/android/en-US/title.txt
          echo "${SHORT_DESCRIPTION:-}" > fastlane/metadata/android/en-US/short_description.txt
          echo "${APP_DESCRIPTION:-}" > fastlane/metadata/android/en-US/full_description.txt
          echo "${RELEASE_NOTES:-Bug fixes and improvements}" > fastlane/metadata/android/en-US/changelogs/default.txt
          cat > fastlane/Fastfile << 'EOF'
          default_platform(:android)
          platform :android do
            lane :deploy do
              artifact_path = File.exist?('artifacts/app.aab') ? 'artifacts/app.aab' : 'artifacts/app.apk'
              is_aab = artifact_path.end_with?('.aab')
              upload_to_play_store(
                package_name: ENV['PACKAGE_NAME'],
                json_key: 'google-play-key.json',
                track: ENV['SUPPLY_TRACK'] || 'internal',
                aab: is_aab ? artifact_path : nil,
                apk: is_aab ? nil : artifact_path,
                release_status: 'draft',
                skip_upload_images: true,
                skip_upload_screenshots: true,
                metadata_path: 'fastlane/metadata/android'
              )
            end
          end
          EOF
      - name: Submit to Google Play
        script: cd fastlane && fastlane android deploy
    publishing:
      scripts:
        - name: Update submission status
          script: |
            if [ "$CM_BUILD_STEP_STATUS" == "success" ]; then
              STATUS="submitted"
            else
              STATUS="failed"
            fi
            echo "Updating submission status to: $STATUS"
            curl -X POST "$SUPABASE_URL/functions/v1/store-submission-webhook" \
              -H "Content-Type: application/json" \
              -H "Authorization: Bearer $SUPABASE_SERVICE_ROLE_KEY" \
              -d "{
                \"submissionId\": \"$SUBMISSION_ID\",
                \"status\": \"$STATUS\",
                \"platform\": \"android\",
                \"buildId\": \"$CM_BUILD_ID\"
              }"

  ios-submit:
    name: iOS App Store Submission
    max_build_duration: 45
    instance_type: mac_mini_m2
    environment:
      xcode: latest
      ruby: 3.2
    scripts:
      - name: Download artifact
        script: |
          mkdir -p artifacts
          echo "Downloading IPA from: $ARTIFACT_URL"
          curl -L -o artifacts/app.ipa "$ARTIFACT_URL"
          ls -la artifacts/
      - name: Setup App Store Connect credentials
        script: |
          mkdir -p ~/.appstoreconnect/private_keys
          echo "$APP_STORE_CONNECT_API_KEY_CONTENT" | base64 -d > ~/.appstoreconnect/private_keys/AuthKey_${APP_STORE_CONNECT_API_KEY_ID}.p8
          chmod 600 ~/.appstoreconnect/private_keys/AuthKey_${APP_STORE_CONNECT_API_KEY_ID}.p8
          echo "App Store Connect credentials configured"
      - name: Install Fastlane
        script: gem install fastlane
      - name: Upload to App Store Connect
        script: |
          cat > /tmp/api_key.json << EOF
          {
            "key_id": "$APP_STORE_CONNECT_API_KEY_ID",
            "issuer_id": "$APP_STORE_CONNECT_ISSUER_ID",
            "key_filepath": "$HOME/.appstoreconnect/private_keys/AuthKey_${APP_STORE_CONNECT_API_KEY_ID}.p8"
          }
          EOF
          fastlane pilot upload \
            --ipa artifacts/app.ipa \
            --api_key_path /tmp/api_key.json \
            --skip_waiting_for_build_processing
    publishing:
      scripts:
        - name: Update submission status
          script: |
            if [ "$CM_BUILD_STEP_STATUS" == "success" ]; then
              STATUS="submitted"
            else
              STATUS="failed"
            fi
            echo "Updating submission status to: $STATUS"
            curl -X POST "$SUPABASE_URL/functions/v1/store-submission-webhook" \
              -H "Content-Type: application/json" \
              -H "Authorization: Bearer $SUPABASE_SERVICE_ROLE_KEY" \
              -d "{
                \"submissionId\": \"$SUBMISSION_ID\",
                \"status\": \"$STATUS\",
                \"platform\": \"ios\",
                \"buildId\": \"$CM_BUILD_ID\"
              }"
