workflows:

  android-release:
    name: Android Release Build
    max_build_duration: 60
    instance_type: linux_x2

    environment:
      java: 17
      node: 20
      vars:
        ANDROID_KEYSTORE_PASSWORD: $ANDROID_KEYSTORE_PASSWORD
        ANDROID_KEY_ALIAS: $ANDROID_KEY_ALIAS
        ANDROID_KEY_PASSWORD: $ANDROID_KEY_PASSWORD
      android_signing:
        - appship_keystore

    scripts:
      - name: Download and extract project
        script: |
          echo "Downloading project from: $APP_ZIP_URL"
          curl -L -o project.zip "$APP_ZIP_URL"
          unzip -o project.zip -d ./app
          cd app
          if [ -d "capacitor-project" ]; then
            mv capacitor-project/* .
            rm -rf capacitor-project
          fi
          ls -la

      - name: Install dependencies
        script: |
          cd app
          npm ci || npm install

      - name: Add and sync Capacitor
        script: |
          cd app
          npx cap add android || true
          npx cap sync android

      - name: Build Android
        script: |
          cd app/android
          chmod +x gradlew
          ./gradlew assembleRelease

    artifacts:
      - app/android/app/build/outputs/**/*.apk
      - app/android/app/build/outputs/**/*.aab

    publishing:
      scripts:
        - name: Notify build result
          script: |
            if [ "$CM_BUILD_STEP_STATUS" == "success" ]; then
              STATUS="finished"
            else
              STATUS="failed"
            fi
            curl -X POST "$SUPABASE_URL/functions/v1/codemagic-webhook" \
              -H "Content-Type: application/json" \
              -d "{
                \"buildId\": \"$CM_BUILD_ID\",
                \"status\": \"$STATUS\",
                \"platform\": \"android\",
                \"workflowId\": \"android-release\",
                \"environment\": {\"variables\": {\"USER_APP_ID\": \"$USER_APP_ID\"}},
                \"artefacts\": [{\"url\": \"$CM_ARTIFACT_LINKS\", \"type\": \"apk\"}],
                \"finishedAt\": \"$(date -u +%Y-%m-%dT%H:%M:%SZ)\"
              }"

  ios-release:
    name: iOS Release Build
    max_build_duration: 90
    instance_type: mac_mini_m2

    environment:
      xcode: latest
      node: 20
      cocoapods: default

    scripts:
      - name: Download and extract project
        script: |
          echo "Downloading project from: $APP_ZIP_URL"
          curl -L -o project.zip "$APP_ZIP_URL"
          unzip -o project.zip -d ./app
          cd app
          if [ -d "capacitor-project" ]; then
            mv capacitor-project/* .
            rm -rf capacitor-project
          fi
          ls -la

      - name: Install dependencies
        script: |
          cd app
          npm ci || npm install

      - name: Add and sync Capacitor
        script: |
          cd app
          npx cap add ios || true
          npx cap sync ios

      - name: Install CocoaPods
        script: |
          cd app/ios/App
          pod install

      - name: Set up code signing
        script: |
          keychain initialize
          echo "$APP_STORE_CONNECT_KEY_CONTENT" | base64 --decode > /tmp/AuthKey.p8
          app-store-connect fetch-signing-files "$BUNDLE_ID" \
            --type IOS_APP_STORE \
            --key-id "$APP_STORE_CONNECT_KEY_ID" \
            --issuer-id "$APP_STORE_CONNECT_ISSUER_ID" \
            --private-key @/tmp/AuthKey.p8 \
            --create
          keychain add-certificates
          xcode-project use-profiles

      - name: Build iOS
        script: |
          cd app/ios/App
          xcodebuild -workspace App.xcworkspace \
            -scheme App \
            -configuration Release \
            -archivePath build/App.xcarchive \
            archive
          xcodebuild -exportArchive \
            -archivePath build/App.xcarchive \
            -exportPath build \
            -exportOptionsPlist exportOptions.plist

    artifacts:
      - app/ios/App/build/*.ipa
      - app/ios/App/build/*.xcarchive

    publishing:
      scripts:
        - name: Notify build result
          script: |
            if [ "$CM_BUILD_STEP_STATUS" == "success" ]; then
              STATUS="finished"
            else
              STATUS="failed"
            fi
            curl -X POST "$SUPABASE_URL/functions/v1/codemagic-webhook" \
              -H "Content-Type: application/json" \
              -d "{
                \"buildId\": \"$CM_BUILD_ID\",
                \"status\": \"$STATUS\",
                \"platform\": \"ios\",
                \"workflowId\": \"ios-release\",
                \"environment\": {\"variables\": {\"USER_APP_ID\": \"$USER_APP_ID\"}},
                \"artefacts\": [{\"url\": \"$CM_ARTIFACT_LINKS\", \"type\": \"ipa\"}],
                \"finishedAt\": \"$(date -u +%Y-%m-%dT%H:%M:%SZ)\"
              }"



