// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://jdkogqskjsmwlhigaecb.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Impka29ncXNranNtd2xoaWdhZWNiIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTMzNzQzMTgsImV4cCI6MjA2ODk1MDMxOH0.RnNRA_bChZsszh3-17APddTFJatM20RVPSACEoPLelE";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

// Some environments can throw on localStorage (privacy mode, strict settings, embedded contexts).
// A safe adapter prevents auth initialization from hanging.
const safeStorage = {
  getItem: (key: string) => {
    try {
      return localStorage.getItem(key);
    } catch {
      return null;
    }
  },
  setItem: (key: string, value: string) => {
    try {
      localStorage.setItem(key, value);
    } catch {
      // no-op
    }
  },
  removeItem: (key: string) => {
    try {
      localStorage.removeItem(key);
    } catch {
      // no-op
    }
  },
};

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: safeStorage,
    persistSession: true,
    autoRefreshToken: true,
  },
});

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});